#!/usr/bin/env python3
"""Build script: compile TypeScript → bundle.js → embed into html.py.

Usage:
    cd dashboard
    npm install        # first time only
    python build.py    # builds and writes python/src/dashboard/html.py
"""

import subprocess
import sys
from pathlib import Path

DASHBOARD_DIR = Path(__file__).parent
REPO_ROOT = DASHBOARD_DIR.parent
DIST_DIR = DASHBOARD_DIR / "dist"
HTML_PY = REPO_ROOT / "python" / "src" / "dashboard" / "html.py"
CSS_FILE = DASHBOARD_DIR / "src" / "styles.css"


def build_js(*, minify: bool = True) -> str:
    """Run esbuild to bundle TypeScript into a single JS string."""
    cmd = [
        "npx", "esbuild",
        "src/main.ts",
        "--bundle",
        "--format=iife",
        f"--outfile={DIST_DIR / 'bundle.js'}",
    ]
    if minify:
        cmd.append("--minify")

    subprocess.run(cmd, cwd=DASHBOARD_DIR, check=True)
    return (DIST_DIR / "bundle.js").read_text()


def read_css() -> str:
    """Read the CSS file."""
    return CSS_FILE.read_text()


def read_html_template() -> str:
    """Return the HTML template with {css} and {js} placeholders."""
    return (DASHBOARD_DIR / "src" / "template.html").read_text()


def generate_html_py(html: str) -> str:
    """Generate the html.py Python file with the full HTML embedded."""
    # Escape backslashes and triple-quotes for safe embedding in a Python string
    escaped = html.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    lines = [
        '"""Embedded dashboard HTML — auto-generated by dashboard/build.py.',
        'Do not edit manually."""',
        "",
        "",
        "def get_dashboard_html() -> str:",
        f'    return """{escaped}"""',
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    minify = "--no-minify" not in sys.argv

    print("Building TypeScript...")
    js = build_js(minify=minify)
    print(f"  bundle.js: {len(js)} bytes")

    print("Reading CSS...")
    css = read_css()
    print(f"  styles.css: {len(css)} bytes")

    print("Assembling HTML...")
    template = read_html_template()
    html = template.replace("{css}", css).replace("{js}", js)
    print(f"  HTML: {len(html)} bytes")

    print("Writing html.py...")
    py = generate_html_py(html)
    HTML_PY.write_text(py)
    print(f"  html.py: {len(py)} bytes")
    print("Done!")


if __name__ == "__main__":
    main()
